- hosts: <<host-ip>>
  tasks:
    - name: Get all Storage VMs
      StorageVMModule: host=<<nslm or apis server-ip>> port=8443 user=<<admin>> password=<<password>> action=get name=ORACLENFS_QA
      register: jsonResultforSVMs

    - name: print the SVM key
      debug: msg="{{ jsonResultforSVMs.meta.result.records[0].key}}"

    - name: Get all Storage Service Levels
      StorageServiceLevelModule: host=<<nslm or apis server-ip>> port=8443 user=<<admin>> password=<<password>> action=get name='Extreme Performance'
      register: jsonResultforSSLs

    - name: print the SSL key
      debug: msg="{{ jsonResultforSSLs.meta.result.records[0].key}}"

    - name: Provision File Share
      FileShareModule:
                host=<<nslm or apis server-ip>>
                port=8443
                user=<<admin>> 
                password=<<password>>
                action=post
                name=ansibleFileShare1
                size=204803008
                storage_vm_key="{{ jsonResultforSVMs.meta.result.records[0].key}}"
                storage_service_level_key="{{ jsonResultforSSLs.meta.result.records[0].key}}"
      register : jsonResult

    - name: print the job key
      debug : msg="{{ jsonResult.meta.result.records[0].key}}"

    - name: loop for status
      JobScheduleModule: host=<<nslm or apis server-ip>> port=8443 user=<<admin>> password=<<password>> action=get key={{ jsonResult.meta.result.records[0].key}}
      register : jsonResult
      until:  (jsonResult.meta.result.records[0].status == "COMPLETED") or (jsonResult.meta.result.records[0].status == "FAILED")
      retries: 5
      delay: 10

    - name: Find Provisioned File Share Key
      FileShareModule:
                host=<<nslm or apis server-ip>>
                port=8443
                user=<<admin>> 
                password=<<password>>
                action=get
                name=ansibleFileShare
      register : jsonResultforFileShare


    - name: print the file share key
      debug: msg="{{ jsonResultforFileShare.meta.result.records[0].key}}"


    - name: Find Export Policy
      ExportPolicyModule:
                host=<<nslm or apis server-ip>>
                port=8443
                user=<<admin>> 
                password=<<password>>
                action=get
                name=ansibleExportPolicy
      register : jsonResultforExportPolicy


    - name: print the export policy key
      debug: msg="{{ jsonResultforExportPolicy.meta.result.records[0].key}}"

    - name: Provision NFS Share
      NFSShareModule:
                host=<<nslm or apis server-ip>>
                port=8443
                user=<<admin>> 
                password=<<password>>
                action=post
                export_policy_key="{{ jsonResultforExportPolicy.meta.result.records[0].key}}"
                file_share_key="{{ jsonResultforFileShare.meta.result.records[0].key}}"
      register : jsonResult

    - name: print the job key
      debug : msg="{{ jsonResult.meta.result.records[0].key}}"

    - name: loop for status
      JobScheduleModule: host=<<nslm or apis server-ip>> port=8443 user=<<admin>> password=<<password>> action=get key={{ jsonResult.meta.result.records[0].key}}
      register : jsonResult
      until:  (jsonResult.meta.result.records[0].status == "COMPLETED") or (jsonResult.meta.result.records[0].status == "FAILED")
      retries: 5
      delay: 10


    - name: start nfs service
      command: service nfs start

    - name: make directory
      command: mkdir /NFSmnt

    - name: mount the nfs share
      command: mount -t nfs <<host-ip>>:/ansibleFileShare /NFSmnt -o nfsvers=3